language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

script:
  - composer install --no-interaction --prefer-source
  - phpunit --coverage-text

notifications:
  email: "m.reza.maghool@gmail.com"